use_frameworks!

platform :ios, '9.0'

target 'SimpleCardView-SwiftUI_Example' do
  pod 'SimpleCardView-SwiftUI', :path => '../'

  target 'SimpleCardView-SwiftUI_Tests' do
    inherit! :search_paths

    
  end
end
